### ISSUE TITLE
Release 2022.06.02 does not work with the latest naemon version 1.4.2

### ISSUE THREAD

**Issue by savv3** [ITRS-Group/monitor-merlin#159]
Getting the following error:
Error: Could not load module '/usr/lib64/merlin/merlin.so' -> /usr/lib64/merlin/merlin.so: undefined symbol: comment_list

Naemon release 1.4.2 has the following changes:
https://github.com/naemon/naemon-core/releases/tag/v1.4.2

I've tried compiling from source, using naemon 1.4.2 but getting errors 
```
module/module.c:681:21: error: 'comment' has no member named 'nexthash'
     next_cmnt = cmnt->nexthash;
                     ^
module/module.c:690:16: error: 'comment_list' undeclared (first use in this function)
    for (cmnt = comment_list; cmnt; cmnt = next_cmnt) {
```
Commenting out those rows will allow compile to work. And naemon will start after that.

**Comment by eschoeller** [comment]
I have run into the same problem. But I was not able to comment out line 681 and the entire for() at line 690. This yielded another error and I didn't dig into it any further. For now I have held back naemon to version 1.4.1. I hope the fix is easy and a new release can be made, which should also address issue #158

**Comment by eschoeller** [comment]
Are there any updates on this?

**Comment by dirtyren** [comment]
Hey guys, I have patched merlin to compile for naemon 1.4.2 and I'd appreciate if someone would try it to see if everything is working fine.

https://github.com/dirtyren/monitor-merlin/tree/naemon-1.4.2

**Comment by eschoeller** [comment]
Great news! I will give this a try in the next week or so.
